apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  QUEUE_NAME: {{ .Values.config.queueName | quote }}
  MAX_RETRIES: {{ .Values.config.maxRetries | quote }}

  {{- if .Values.redis.host }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  {{- else }}
  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  {{- end }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
