{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "demo-app.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.ingress.pathPrefix }}`)
      kind: Rule
      services:
        - name: {{ include "demo-app.fullname" . }}-api
          port: 80
      middlewares:
        - name: {{ include "demo-app.fullname" . }}-stripprefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "demo-app.fullname" . }}-stripprefix
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.pathPrefix }}
{{- end }}
