apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
